### ISSUE TITLE
Data-type -> GeometryBase

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas-actions.ghpython_components#11]
Hi,

I think, there is no type for GeometryBase from the default list below.
How can I add a geometry-base type to this list?

Thank you :) 

![image](https://user-images.githubusercontent.com/18013985/231839065-fbc739e7-01c6-438e-82a5-a0e6e1f326ac.png)

**Comment by gonzalocasas** [comment]
Added on https://github.com/compas-dev/compas-actions.ghpython_components/commit/ad34933f7202155d8b91667efd689d24ca076aca and available on the latest release

**Comment by petrasvestartas** [comment]
thank you
