### ISSUE TITLE
Any plans for updating to Python3?

### ISSUE THREAD

**Issue by 9and3** [compas-dev/compas-actions.ghpython_components#12]
Hello!

Big fan of the action and loved the brilliant way to generate `.ghuser` components from python and allow easy ci. Thanks!

I was wondering if there were any plans to update this to Python3 with the new Script component of Grasshopper.

I quickly got a look at the python and use pythonnet to replace some functionnalities of IronPython  (e.g. the `clr` module's `clr.AddReference(gh_io)`), and it outputs the `.ghuser` files but they are still marked as "old" if imported into the grasshopper canvas.
 
Would you have any clue how to modify the `componentize.py` file to port this properly to the new CPython Script component? Would love to give it a go and open a PR if of any utility.

Cheers!

**Comment by gonzalocasas** [comment]
> I was wondering if there were any plans to update this to Python3 with the new Script component of Grasshopper.

Yes, definitely!

> Would you have any clue how to modify the componentize.py file to port this properly to the new CPython Script component?

There's a bit of reverse engineering required to understand what are the correct guids and structure that is required for the new script component. One way of exploring this is by saving GH files to GHX and exploring the xml version to figure details out.

> Would love to give it a go and open a PR if of any utility.

That would be amazing!

**Comment by 9and3** [comment]
Thanks for the reply @gonzalocasas ! I see, I can't promise anything on how much I will be able to find time and get the new structure but I'll give it a go. I'll open a PR as soon as I will start munching this:)

**Comment by 9and3** [comment]
@gonzalocasas menaged to have a first decent draft for the porting in a new PR: #13 
Closing this one if fine for you!
