### ISSUE TITLE
 Cannot find GH_IO Assembly! Aborting

### ISSUE THREAD

**Issue by Marco-Pellegrino** [compas-dev/compas-actions.ghpython_components#3]
Hello :)

I am running the componentize from my machine and it looks like that GH_IO needs to be inside the folder ./lib
I would suggest to look for the GH_IO in the same folder where the .py is runned.

**Comment by Marco-Pellegrino** [comment]
This folder structure seems to work but we should probably specify it in the repository

![image](https://user-images.githubusercontent.com/53620289/140842551-cc9f1a2a-e590-4e48-bc2b-6993b273997b.png)

**Comment by gonzalocasas** [comment]
Starting now, when the action is run locally, it will no longer try to find a local version of `GH_IO.dll` and instead (if not manually specified), it will automatically download it from NuGet. I hope this makes it easier to use!
