### ISSUE TITLE
Descriptions missing in procedural mode.

### ISSUE THREAD

**Issue by funkchaser** [compas-dev/compas-actions.ghpython_components#5]
I created a definition for a component in the procedural mode (`"isAdvancedMode": false`). 

**What's wrong?** 
In the built component all `"description"` values are ignored and a default text is displayed instead, except for the very first input parameter.

**Example/Demo**
`code.py` contains only:
`c = a+b`

`metadata.json`:

```
{
    "name": "TestSum",
    "nickname": "TestSum",
    "category": "Componentizer",
    "subcategory": "Test",
    "description": "Tests if the componentizer is working in procedural mode.",
    "exposure": 4,
    "ghpython": {
        "isAdvancedMode": false,
        "iconDisplay": 0,
        "inputParameters": [
            {
                "name": "a",
                "description": "First number",
                "typeHintID": "float",
                "scriptParamAccess": 0
            },
            {
                "name": "b",
                "description": "Second number",
                "typeHintID": "float",
                "scriptParamAccess": 0
            }

        ],
        "outputParameters": [
            {
                "name": "c",
                "description": "Sum of a and b."
            }
        ]
    }
}
```

**Preview:**
Correct:
![image](https://user-images.githubusercontent.com/11560512/185912706-12d198aa-4d2b-43a8-aeb6-3dab4d0caa1f.png)
Wrong/default:
![image](https://user-images.githubusercontent.com/11560512/185912810-0e64d004-3882-44ae-97dc-63b8978ad6c8.png)
![image](https://user-images.githubusercontent.com/11560512/185913010-3b7c7874-46ac-405d-8388-763d1443e150.png)

**Comment by gonzalocasas** [comment]
And done!
