### ISSUE TITLE
Add Flatten/Graft/Symplify/Reverse

### ISSUE THREAD

**Issue by funkchaser** [compas-dev/compas-actions.ghpython_components#6]
**Feature Request:**

It some situations it would be helpful to set, for example, a "Flatten" action on the input params as default, so that certain assumptions about the structure of the input can be imposed. 
Would it be possible to add a corresponding flag to the metadata?

![image](https://user-images.githubusercontent.com/11560512/185916343-725a2a10-3a0d-4d32-add2-b5d12b607d69.png)

**Comment by gonzalocasas** [comment]
Done
